/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Service_constants.h"



const ServiceConstants g_Service_constants;

ServiceConstants::ServiceConstants() {
}



